# Generated by Django 4.2.6 on 2023-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_description', models.TextField(blank=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"PLATFORM"."USER"',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('user', models.OneToOneField(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.user')),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('caregiving_type', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_applied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"PLATFORM"."CAREGIVER"',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.user')),
                ('house_rules', models.TextField(blank=True)),
            ],
            options={
                'db_table': '"PLATFORM"."MEMBER"',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member', models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.member')),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': '"PLATFORM"."ADDRESS"',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('member', models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.member')),
                ('required_caregiving_type', models.CharField(blank=True, max_length=50)),
                ('other_requirements', models.TextField(blank=True)),
                ('date_posted', models.DateField()),
            ],
            options={
                'db_table': '"PLATFORM"."JOB"',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('caregiver', models.OneToOneField(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.caregiver')),
                ('date_applied', models.DateField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caregiving_app.job')),
            ],
            options={
                'db_table': '"PLATFORM"."JOB_APPLICATION"',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('caregiver', models.OneToOneField(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregiving_app.caregiver')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('work_hours', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('member', models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, to='caregiving_app.member')),
            ],
            options={
                'db_table': '"PLATFORM"."APPOINTMENT"',
            },
        ),
    ]
